# Site settings
title:          Hana
description:    "Minimal Jekyll theme for storytellers"
url:            "https://hanabiii.github.io"

# Author
author:
  name:         Hana
  url:          https://hanabiii.github.io
  email:        andywangsy@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
